networks:
  test_network:
    name: test_network
    driver: bridge

services:
  test-db:
    image: postgres:15-alpine3.17
    restart: always
    env_file: .env
    container_name: test-db
    environment:
      POSTGRES_DB: ${PGSQL_NAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_USER: ${PGSQL_USER}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${PGSQL_PORT}:${PGSQL_PORT}
    networks:
      - test_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PGSQL_USER} -d ${PGSQL_NAME}']
      interval: 10s
      timeout: 3s
      retries: 3
